package com.svp;

import android.app.Application;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.util.Log;
import android.widget.Button;


import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.support.ConnectionSource;
import com.j256.ormlite.table.TableUtils;
import com.svp.db.ormlite.DatabaseOrmLiteHelper;

import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;

/**
 * Created by Pasha on 3/22/2016.
 */
public class App extends Application{

    @Override
    public void onCreate(){
        super.onCreate();
        DatabaseOrmLiteHelper db = new TetDb(this);

//        Button b = new Button(this);
//        b.setOnClickListener(v->v.setBackgroundResource(0));

    }

    public class TetDb extends DatabaseOrmLiteHelper{

        public TetDb(Context context) {
            super(context, "tb_name", 1);
        }

        @Override
        protected void onTableCreate(SQLiteDatabase db, ConnectionSource connectionSource) {
            try {
                TableUtils.createTable(connectionSource, SimpleData.class);
            } catch (SQLException e) {
                //Log.e(className, "Can't drop databases", e);
                throw new RuntimeException(e);
            }
        }

        @Override
        protected void onTableUpdate(SQLiteDatabase db, ConnectionSource connectionSource) {
            try {
                TableUtils.dropTable(connectionSource, App.SimpleData.class, true);
            } catch (SQLException e) {
            }
        }
    }
    public class SimpleData {

        // id is generated by the database and set on the object automagically
        @DatabaseField(generatedId = true)
        int id;
        @DatabaseField(index = true)
        String string;
        @DatabaseField
        long millis;
        @DatabaseField
        Date date;
        @DatabaseField
        boolean even;

        SimpleData() {
            // needed by ormlite
        }

        public SimpleData(long millis) {
            this.date = new Date(millis);
            this.string = (millis % 1000) + "ms";
            this.millis = millis;
            this.even = ((millis % 2) == 0);
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append("id=").append(id);
            sb.append(", ").append("str=").append(string);
            sb.append(", ").append("ms=").append(millis);
            SimpleDateFormat dateFormatter = new SimpleDateFormat("MM/dd HH:mm:ss", Locale.US);
            sb.append(", ").append("date=").append(dateFormatter.format(date));
            sb.append(", ").append("even=").append(even);
            return sb.toString();
        }
    }
}
